//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public string CompanyID { get; set; }
        public string InvestID { get; set; }
        public string InvestType { get; set; }
        public int InvPercent { get; set; }
        public string DirectRel { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int NoShares_YN { get; set; }
    
        public virtual CompanyName CompanyName { get; set; }
        public virtual InvestmentType InvestmentType { get; set; }
    }
}
