//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidiary
    {
        public string CompanyID { get; set; }
        public string SubsiID { get; set; }
        public string SubType { get; set; }
        public int SubPercent { get; set; }
        public string DirectRel { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int NoShares_YN { get; set; }
    
        public virtual CompanyName CompanyName { get; set; }
        public virtual SubsidiariesType SubsidiariesType { get; set; }
    }
}
